from django.contrib import admin

from .models import *

admin.site.register(Banda)
admin.site.register(Usuario)
admin.site.register(Normal)
admin.site.register(Artista)
admin.site.register(Mensaje)
admin.site.register(Administrador)
admin.site.register(Comentario)
admin.site.register(Reporte)
admin.site.register(Notificacion)
admin.site.register(Instrumento)
admin.site.register(IntegrantesBanda)
admin.site.register(Genero)
admin.site.register(Cancion)
admin.site.register(Evento)
admin.site.register(Noticia)
admin.site.register(Material)
admin.site.register(Calificacion)
admin.site.register(MensajeBanda)
admin.site.register(Toca)
admin.site.register(Solicitud)
admin.site.register(Disco) 